config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "pages#home"
  get "/salut", to: "pages#salut", as: "salut"
  #get "/salut/:name", to: "pages#salutto", as: "to"
  #parametre optionnel
  #get "/coucou(/:name)", to: "pages#coucou", as: "coucou"
  #get "/posts", to: "posts#index", as: "post_index"
  resources :posts, only: [:index, :show, :edit, :update, :create]
end

app/models/Post.rb
class Post < ApplicationRecord

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def salut
    end

    def home
    end

    def salutto
        @name = params[:name]
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
  def show
    @post = Post.find(params[:id])
  end
  def edit
    @post = Post.find(params[:id])
  end
  def update
    @post = Post.find(params[:id])
    post_params = params.require(:post).permit(:name, :content)
    @post.update(post_params)
    redirect_to post_path(@post.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <div class="container">
          <a class="navbar-brand" href="#">Navbar</a>
          <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="<%= root_path %>">Home</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="<%= salut_path(name: 'ayoub') %>">Salut</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="<%= posts_path %>">Posts</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container py-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h3>Home Page</h3>

app/views/pages/salut.html.erb
<h1>Salut tous le monde</h1>

app/views/pages/salutto.html.erb
<h4>Salut à <%= @name %></h4>
<%= params.inspect %>

app/views/posts/edit.html.erb
<h4>Edit Post</h4>

<%= form_for @post do |f| %>
    <div class="form-group">
        <label>Name</label>
        <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
        <label>Content</label>
        <%= f.text_area :content, class: "form-control" %>
    </div>
    <button type="submit" class="btn btn-success">Update</button>
<% end %>

app/views/posts/index.html.erb
<h5>Mes posts</h5>
<hr/>
<% @posts.each do |p| %>
    <div class="card">
        <div class="card-body">
            <h4><%= p.name %></h4>
            <p class="m-0">
                <a class="btn btn-primary btn-sm" href="<%= post_path(p.id)%>">Show</a>
            </p>
        </div>
    </div>
<% end %>

app/views/posts/show.html.erb
<h4><%= @post.name %></h4>
<a class="btn btn-warning btn-sm" href="<%= edit_post_path(@post.id) %>">Edit</a>